### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by azamet90** [dalunacrobate/DaProfiler#21]
```
Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\DaProfiler\profiler.py", line 504, in <module>
    webui()
  File "C:\Users\xxx\Downloads\DaProfiler\profiler.py", line 488, in webui
    y = json.loads(x.text)
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err. Value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

:-/

**Comment by Sn0wAlice** [comment]
did you read the fucking other issue: MOUVED TO URL ?
