### ISSUE TITLE
requests.exceptions.InvalidURL: Failed to parse

### ISSUE THREAD

**Issue by EyupErgin** [dalunacrobate/DaProfiler#3]
Hello there! While reviewing your Github profile, I wanted to take a look at a project you are still working on.
I downloaded it to my personal computer to see how the program works. Besides, I executed all the commands like you added to the readme file. However, I encountered the following error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 379, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://fr-fr.facebook.com/public/....-....
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "profiler.py", line 55, in <module>
    facebook_results = facebook_search.facebook_search(name=name,pren=pren)
  File "/home/*****/Masaüstü/DaProfiler/modules/facebook_search.py", line 6, in facebook_search
    page = requests.get(url).content.decode('utf-8')
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 381, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL:https://fr-fr.facebook.com/public/....-.....

It seems that the library you are using is no longer supported or it may have been upgraded to a new version. I wanted to report the error. You can solve the error by typing the version installed in your requirements.txt file or you can change the codes completely. The simplest way would be to edit the file. Good luck.

**Comment by EyupErgin** [comment]
In fact, when I did a little research on the source of the problem, I realized that un-updated libraries are causing problems.

I solved the problem by updating with a simple code.

Code : python3 -m pip3 install --upgrade urllib3
