### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by shanow7** [dalunacrobate/DaProfiler#4]
DaProfiler$ python3 profiler.py -n Jean -ln reno

 =====================================
|     Author : Dalunacrobate          |
|  Mail : daluna_pro@protonmail.ch    |
 =====================================

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 980, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dirigeants.bfmtv.com', port=443): Max retries exceeded with url: /recherche/q/reno5+Jean6 (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/osint/DaProfiler/profiler.py", line 38, in <module>
    bfmtv_results = dirigeants_bfmtv.bfmtv_search(name=name,pren=pren)
  File "/home/osint/DaProfiler/modules/dirigeants_bfmtv.py", line 5, in bfmtv_search
    r = requests.get("https://dirigeants.bfmtv.com/recherche/q/{}5+{}6".format(name,pren))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='dirigeants.bfmtv.com', port=443): Max retries exceeded with url: /recherche/q/reno5+Jean6 (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1123)')))

can you help?

**Comment by L14ms111** [comment]
Install the required dependencies before, right? or else the problem comes directly from your version of Python.

**Comment by shanow7** [comment]
yes, I've python 3.9.1 pip 20.3.3

**Comment by dalunacrobate** [comment]
> yes, I've python 3.9.1 pip 20.3.3

Hi, did you tried with another name ? Tbh I don't know from what it come from, I guess you had too much results but maybe I'm saying shit
